title: Kim's νƒκµ¬λ…ΈνΈ
description: 

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/citizenblog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: ybigta-web-dev
   twitter: 
   facebook: 
   email: 

google_analytics: 
